# Use a Python runtime as a base image
FROM --platform=linux/amd64 continuumio/miniconda3:24.9.2-0

# Set the working directory to /app
WORKDIR /app

# Install conda dependencies
RUN conda update -n base conda && \
    conda config --add channels conda-forge && \
    conda config --add channels bioconda && \
    conda config --add channels pypi && \
    conda install -n base conda-libmamba-solver && \
    conda config --set solver libmamba && \
    conda install -y bioconda::minimap2 && \
    conda install -y bioconda::samtools && \
    conda install -c conda-forge ncurses

# Install Python dependencies
RUN pip install flask flask-cors

# Copy the rest of the application code
COPY app.py .

# Expose port 5000
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]